

--Alcools

INSERT INTO produits (id_producteur, id_type2, description, prix, designation, photo, disponible) VALUES 
(6, 10, 'Le côtes-du-rhône villages est un vin d''appellation d''origine contrôlée produit sur une large partie du vignoble de la vallée du Rhône méridionale, sur quatre départements : l''Ardèche, la Drôme, le Gard et le Vaucluse.', 18.00, 'Côtes-du-rhône villages 2001', 'cdr.jpg', true),
(5, 10, 'Le côte-rôtie est un vin rouge d''appellation d''origine contrôlée produit sur les communes d''Ampuis, de Saint-Cyr-sur-le-Rhône et de Tupin-et-Semons, sur la rive droite du Rhône, en face de la ville de Vienne, au sud de Lyon.', 17.8, 'AOC Côte-Roti 2005', 'cote-rotie.jpg', true),
(3, 13, 'La chartreuse est une liqueur d''origine végétale fabriquée par les moines chartreux dans les caves de Voiron en Isère, en bordure du Massif de la Chartreuse. Liqueur au très haut degré d''alcool sa fabrication se fait sous la supervision des moines de la Grande-Chartreuse.', 25.00, 'La Chartreuse', 'chartreuse.jpg', true),
(1, 13, 'La recette de la liqueur de génépi historiquement et universellement (mais pas la meilleure) connue est "40 brins, 40 sucres, 40 jours". En français : faire macérer 40 brins de génépi fleuri dans 1 litre d''alcool à 40° pendant 40 jours et rajouter 40 sucres.', 8.72, 'Liqueur de Genepi Dolin', 'genepi.jpg', true),
(6, 11, 'Le condrieu est un vin blanc d''appellation d''origine contrôlée produit sur la rive droite du Rhône, près de Condrieu, au sud de la ville de Vienne. Il s''agit d''une appellation du vignoble de la vallée du Rhône septentrionale, entre les aires de production du côte-rôtie au nord et du saint-joseph au sud.', 19.60, 'AOC le Condrieu 2011', 'condrieu.jpg', true),
(9, 11, 'Le coteaux-de-die est un vin blanc d''appellation d''origine contrôlée produit dans la haute vallée de la Drôme. Cette AOC désigne des vins blancs secs produits sur la même aire d’appellation que la Clairette de Die.', 18.00, 'AOC le Coteau de Die 2012', 'coteau-de-die.jpg', true),
(6, 12, 'Parfaitement adapté à nos terroirs le Merlot Noir reste le cépage dominant de notre vignoble, dans ce vin, il représente 40%. Le Cabernet Franc apporte ici de la structure et surtout un bouquet délicat, il est présent à 35% et complété par 25% de Cabernet Sauvignon.', 13.50, 'Vin rosé Bergerac 2013', 'vin-rose.jpg', true),
(1, 12, 'Les vins du Vivarais dans le sud-est du Massif central ont une origine assez ancienne qui remonte à l''époque romaine mais son implantation s''est réellement développée au Moyen Âge. Les chemins muletiers, dès le Moyen Âge et jusqu''à la fin du XIXe siècle, ont été utilisés pour monter le vin du bas-Vivarais vers les contrées du Gévaudan, de la Lozère et même vers les plateaux auvergnats (Le Puy).', 18.00, 'AOC Côtes-du-vivarais 2013', 'Côtes_du_Vivarais_rose.jpg', true),
(8, 13, 'La liqueur de gentiane est une boisson apéritive amère et alcoolisée fabriquée par macération et distillation de racines de gentiane jaune d''Auvergne (gentiana lutea) qui lui confèrent son amertume bien spécifique. On retrouve cette plante en importantes quantités dans les monts du Cantal, entre le Puy Mary et le Plomb du Cantal.', 10.00, 'Liqueur de Gentiane', 'gentiane.jpg', true);
