<%@ taglib prefix="fmt"	uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="s"	uri="/struts-tags"%>

<div class="row">
	<h1>A propos</h1>
	
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet consequat enim, eu ornare dolor. Integer ornare fringilla molestie. Nulla ut vulputate nisi, nec ornare metus. Etiam vel purus felis. Nunc ut tortor dolor. Nullam varius tempor ipsum vitae egestas. Nulla luctus lorem a bibendum imperdiet.</p>

	<p>Vivamus vitae maximus tortor, id feugiat metus. Ut pharetra metus molestie lacinia vehicula. Morbi enim ante, dapibus eu metus a, fringilla tempor orci. Morbi accumsan sit amet mi at blandit. Vestibulum ullamcorper congue leo, eget ultrices lorem vulputate ut. Donec scelerisque non turpis consequat varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec iaculis justo id purus congue aliquam. Mauris a malesuada leo, eu ultricies risus. Cras felis orci, aliquam ac tempor dictum, auctor quis tortor. Aliquam fringilla augue sed ex efficitur, vitae consectetur metus auctor. Maecenas risus lacus, sollicitudin eu purus quis, pulvinar scelerisque ante. Praesent sit amet vehicula neque. Nulla facilisi. Praesent euismod, diam bibendum vulputate volutpat, neque quam porttitor velit, in pharetra diam felis ut elit.</p>

	<p>Maecenas consectetur justo sed orci auctor, sed rutrum urna tempor. Praesent in maximus nisi. Sed id porta orci. Etiam cursus rutrum pretium. Mauris tristique laoreet justo id fermentum. Morbi tincidunt imperdiet porttitor. Integer purus nibh, viverra volutpat eleifend vitae, ultricies ut quam. In dui dolor, aliquam ut nulla eget, vestibulum consectetur velit. Vestibulum euismod et mauris bibendum iaculis. Aliquam tempor orci finibus, efficitur mauris sit amet, gravida risus. Integer dictum fermentum lacus, vitae semper dui tristique nec. Etiam pulvinar lorem leo, sed placerat ante rhoncus nec. Pellentesque non erat magna. Suspendisse potenti. Cras imperdiet libero a nibh consectetur, nec consequat metus maximus.</p>

	<p>Fusce tempus metus vitae sapien ornare, id semper mauris sodales. Morbi et placerat libero, ut ornare tellus. Sed aliquam libero quis lorem vestibulum iaculis. Nulla quis est nisi. Aenean venenatis dui aliquam porttitor accumsan. Nam eu ante placerat augue consequat bibendum. Proin ultrices urna et dolor posuere, condimentum laoreet augue consectetur. Nunc ipsum lacus, faucibus in convallis nec, laoreet vel arcu. Duis sed pulvinar lacus. Nullam a tempus dolor. Quisque pharetra consequat est, sed dictum lacus vulputate id. Phasellus sollicitudin rutrum accumsan. Nunc eget quam iaculis, viverra nulla nec, bibendum purus. Vestibulum mattis tortor ipsum, et faucibus ex laoreet vitae. Integer orci quam, dictum id ante at, sodales ornare neque.</p>

	<p>Aliquam sollicitudin mi fringilla mi iaculis tempus. Mauris auctor ipsum quis neque commodo, sit amet ultrices nibh auctor. Ut maximus consectetur augue vel pulvinar. Donec scelerisque vitae velit ut volutpat. Duis magna leo, dapibus eget justo et, varius dignissim est. Ut neque augue, sollicitudin et congue in, congue vel ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
</div>